name = "JuliaXSPEC"
uuid = "3c005aca-6691-4949-923b-87defb3ec510"
version = "0.2.0"
authors = ["Andy Young <andy.young@bristol.ac.uk>"]

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
FFTW = "1"
FITSIO = "0.17"
SpecialFunctions = "2"
julia = "1.13"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
