/* Generated by JuliaXSPEC from the registered models; do not edit.
 *
 * XSPEC calls one of the functions below (named in model.dat with a c_ prefix).
 * Each one makes sure the Julia runtime is started and then hands everything
 * to the single Julia entry point, juliaxspec_evaluate, together with the
 * model name. See src/entry.jl for the Julia side.
 */
#include <stddef.h>
#include "../build/include/julia_init.h"

extern int juliaxspec_evaluate(const char *model, const double *energy, int nflux,
                               const double *params, int spectrum, double *flux,
                               double *flux_error, const char *init);

static void ensure_julia_started(void)
{
    static int started = 0;
    if (!started) {
        init_julia(0, NULL);
        started = 1;
    }
}

/* jlgauss (add): Gaussian line, computed directly (same as XSPEC's gaussian) */
void jlgauss(const double *energy, int nflux, const double *params, int spectrum,
           double *flux, double *flux_error, const char *init)
{
    ensure_julia_started();
    juliaxspec_evaluate("jlgauss", energy, nflux, params, spectrum, flux, flux_error, init);
}

/* jlgausscached (add): The same Gaussian line, interpolated from a cached parameter grid */
void jlgausscached(const double *energy, int nflux, const double *params, int spectrum,
                 double *flux, double *flux_error, const char *init)
{
    ensure_julia_started();
    juliaxspec_evaluate("jlgausscached", energy, nflux, params, spectrum, flux, flux_error, init);
}

/* jlgconv (con): Gaussian blur in g = E_obs / E_em */
void jlgconv(const double *energy, int nflux, const double *params, int spectrum,
           double *flux, double *flux_error, const char *init)
{
    ensure_julia_started();
    juliaxspec_evaluate("jlgconv", energy, nflux, params, spectrum, flux, flux_error, init);
}

/* jlgconvfft (con): Gaussian blur in g, evaluated with an FFT */
void jlgconvfft(const double *energy, int nflux, const double *params, int spectrum,
              double *flux, double *flux_error, const char *init)
{
    ensure_julia_started();
    juliaxspec_evaluate("jlgconvfft", energy, nflux, params, spectrum, flux, flux_error, init);
}

/* jltable (add): xillverD-5 reflection table, interpolated in Julia */
void jltable(const double *energy, int nflux, const double *params, int spectrum,
           double *flux, double *flux_error, const char *init)
{
    ensure_julia_started();
    juliaxspec_evaluate("jltable", energy, nflux, params, spectrum, flux, flux_error, init);
}

/* jltableblur (add): xillver reflection blurred by a Gaussian in g, on the table energy grid */
void jltableblur(const double *energy, int nflux, const double *params, int spectrum,
               double *flux, double *flux_error, const char *init)
{
    ensure_julia_started();
    juliaxspec_evaluate("jltableblur", energy, nflux, params, spectrum, flux, flux_error, init);
}
