# The model registry, and the two files XSPEC needs that are generated from it:
# model.dat (parameter descriptions) and a C file with one tiny wrapper per
# model. Both are derived purely from the registered Julia models, so a user
# never writes C or edits model.dat by hand.

const REGISTRY = AbstractXSPECModel[]

"""
    register!(model) -> model

Make a model available to XSPEC. Models appear in `model.dat` in registration
order. Registering a second model with the same name replaces the first, which
is convenient while developing at the REPL.

Call `register!` from a module's `__init__` (not at top level) so that the
registration happens every time the module is loaded, including when it is
loaded from a precompiled image.
"""
function register!(model::AbstractXSPECModel)
    existing = findfirst(m -> m.name == model.name, REGISTRY)
    if existing === nothing
        push!(REGISTRY, model)
    else
        REGISTRY[existing] = model
    end
    return model
end

"""
    registered_models() -> Vector{AbstractXSPECModel}

All registered models, in `model.dat` order.
"""
registered_models() = copy(REGISTRY)

"""
    lookup_model(name) -> AbstractXSPECModel

The registered model called `name`; errors listing the available names otherwise.
"""
function lookup_model(name::AbstractString)
    i = findfirst(m -> m.name == name, REGISTRY)
    i === nothing && error("no JuliaXSPEC model named $(repr(name)); registered: $(join([m.name for m in REGISTRY], ", "))")
    return REGISTRY[i]
end

"""
    c_function_name(model) -> String

Name of the C function XSPEC calls for this model: the model name with
underscores removed (XSPEC's `initpackage` expects wrapper names without them).
"""
c_function_name(m::AbstractXSPECModel) = replace(m.name, "_" => "")

"""
    model_dat_text(models = registered_models()) -> String

Contents of XSPEC's `model.dat` for these models. Each stanza is a header line

    name nparameters Elow Ehigh c_function type 0

followed by one line per parameter (see [`model_dat_line`](@ref)). Stanzas are
separated by a blank line, which is how XSPEC tells them apart.
"""
function model_dat_text(models::AbstractVector{<:AbstractXSPECModel} = registered_models())
    stanzas = map(models) do m
        header = "$(m.name) $(length(m.parameters)) 0. 1.e20 c_$(c_function_name(m)) $(xspec_type(m)) 0"
        join([header; model_dat_line.(m.parameters)], "\n")
    end
    return join(stanzas, "\n\n") * "\n"
end

"""
    c_wrappers_text(models = registered_models(); julia_init_header) -> String

C source for the XSPEC side of the bridge. It contains one wrapper per model
with XSPEC's C model signature; each wrapper starts Julia if needed and then
calls the single Julia entry point `juliaxspec_evaluate` with the model name.
`julia_init_header` is the path, relative to the generated file, of the
`julia_init.h` header produced by PackageCompiler.
"""
function c_wrappers_text(
    models::AbstractVector{<:AbstractXSPECModel} = registered_models();
    julia_init_header::AbstractString = "../build/include/julia_init.h",
)
    io = IOBuffer()
    print(io, """
        /* Generated by JuliaXSPEC from the registered models; do not edit.
         *
         * XSPEC calls one of the functions below (named in model.dat with a c_ prefix).
         * Each one makes sure the Julia runtime is started and then hands everything
         * to the single Julia entry point, juliaxspec_evaluate, together with the
         * model name. See src/entry.jl for the Julia side.
         */
        #include <stddef.h>
        #include "$julia_init_header"

        extern int juliaxspec_evaluate(const char *model, const double *energy, int nflux,
                                       const double *params, int spectrum, double *flux,
                                       double *flux_error, const char *init);

        static void ensure_julia_started(void)
        {
            static int started = 0;
            if (!started) {
                init_julia(0, NULL);
                started = 1;
            }
        }
        """)
    for m in models
        print(io, """

            /* $(m.name) ($(xspec_type(m)))$(isempty(m.description) ? "" : ": " * m.description) */
            void $(c_function_name(m))(const double *energy, int nflux, const double *params, int spectrum,
                $(" "^length(c_function_name(m)))double *flux, double *flux_error, const char *init)
            {
                ensure_julia_started();
                juliaxspec_evaluate("$(m.name)", energy, nflux, params, spectrum, flux, flux_error, init);
            }
            """)
    end
    return String(take!(io))
end

"""
    write_xspec_package(dir; models = registered_models(), package = "juliaxspec", julia_init_header)

Write `model.dat` and `<package>_wrappers.c` into `dir`, ready for XSPEC's
`initpackage <package> model.dat <dir>`. Returns the two file paths.
"""
function write_xspec_package(
    dir::AbstractString;
    models::AbstractVector{<:AbstractXSPECModel} = registered_models(),
    package::AbstractString = "juliaxspec",
    julia_init_header::AbstractString = "../build/include/julia_init.h",
)
    isempty(models) && error("no models registered; nothing to write")
    cnames = c_function_name.(models)
    allunique(cnames) || error("model names collide after removing underscores: $(join(cnames, ", "))")
    mkpath(dir)
    model_dat = joinpath(dir, "model.dat")
    wrappers = joinpath(dir, "$(package)_wrappers.c")
    write(model_dat, model_dat_text(models))
    write(wrappers, c_wrappers_text(models; julia_init_header))
    return model_dat, wrappers
end
